import { StyleSheet } from 'react-native';
import * as calendarHelpers from './calendarHelpers';

const { TIME_WHEEL_ITEM_HEIGHT, TIME_WHEEL_SIDE_ROWS } = calendarHelpers;

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#fff' },
  container: { paddingHorizontal: 18, paddingTop: 12 },

  header: { marginBottom: 16 },
  title: { fontSize: 22, fontWeight: '800', color: '#111827' },
  subtitle: { marginTop: 6, fontSize: 12, color: '#6b7280' },
  subtitleStrong: { color: '#111827', fontWeight: '700' },

  card: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 14,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  label: { fontSize: 12, fontWeight: '700', color: '#374151' },
  input: {
    marginTop: 6,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    color: '#111827',
    backgroundColor: '#f9fafb',
  },
  inputHint: {
    marginTop: 6,
    fontSize: 11,
    color: '#6b7280',
  },
  buttonRow: {
    marginTop: 14,
    flexDirection: 'row',
    gap: 10,
  },
  primaryBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: '#111827',
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryBtnText: { color: '#fff', fontWeight: '700', fontSize: 13 },
  ghostBtn: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  ghostBtnText: { color: '#111827', fontWeight: '700', fontSize: 13 },
  helper: { marginTop: 10, fontSize: 11, color: '#9ca3af' },
  error: { marginTop: 8, fontSize: 12, color: '#ef4444' },
  sync: { marginTop: 8, fontSize: 11, color: '#6b7280' },

  previewSection: {
    marginTop: 18,
    borderRadius: 28,
    backgroundColor: '#f7f4ef',
    padding: 16,
    borderWidth: 1,
    borderColor: '#ece6dc',
  },
  previewFocusRow: {
    marginTop: 16,
    flexDirection: 'column',
    gap: 14,
    alignItems: 'stretch',
  },
  focusTodayCard: {
    width: '100%',
    borderRadius: 28,
    backgroundColor: '#111827',
    paddingHorizontal: 22,
    paddingVertical: 20,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    shadowColor: '#0f172a',
    shadowOpacity: 0.14,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  focusTodayLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: '#f9fafb',
    opacity: 0.72,
    letterSpacing: 1,
  },
  focusTodayDate: {
    marginTop: 10,
    fontSize: 28,
    fontWeight: '900',
    color: '#fff',
  },
  focusTodayMeta: {
    marginTop: 10,
    fontSize: 14,
    lineHeight: 20,
    color: '#d1d5db',
  },
  previewHeaderRow: {
    gap: 12,
  },
  previewHeaderTextWrap: {
    gap: 4,
  },
  previewEyebrow: {
    fontSize: 11,
    letterSpacing: 1.1,
    fontWeight: '800',
    color: '#8a7963',
  },
  previewTitle: {
    fontSize: 23,
    lineHeight: 28,
    fontWeight: '900',
    color: '#1f2937',
  },
  previewSubtitle: {
    fontSize: 12,
    lineHeight: 18,
    color: '#6b7280',
  },
  previewTabRow: {
    flexDirection: 'row',
    alignSelf: 'flex-start',
    gap: 10,
  },
  previewTab: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ddd6ca',
  },
  previewTabActive: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#111827',
  },
  previewTabActiveText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#fff',
    textTransform: 'capitalize',
  },
  previewTabText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#1f2937',
    textTransform: 'capitalize',
  },
  miniCalendarCard: {
    width: '100%',
    borderRadius: 28,
    backgroundColor: '#111827',
    paddingHorizontal: 22,
    paddingTop: 20,
    paddingBottom: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    shadowColor: '#0f172a',
    shadowOpacity: 0.16,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  miniCalendarTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  miniCalendarTitleBtn: {
    flex: 1,
    paddingRight: 12,
  },
  miniCalendarTitle: {
    fontSize: 20,
    lineHeight: 24,
    fontWeight: '900',
    color: '#fff',
  },
  miniCalendarTitleHint: {
    marginTop: 4,
    fontSize: 10,
    fontWeight: '700',
    color: '#9ca3af',
  },
  miniCalendarNavRow: {
    flexDirection: 'row',
    gap: 8,
  },
  miniCalendarNavBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.10)',
  },
  miniCalendarNavText: {
    fontSize: 22,
    fontWeight: '800',
    color: '#fff',
  },
  miniCalendarWeekdays: {
    marginTop: 16,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  miniCalendarWeekdayText: {
    width: '14.2857%',
    textAlign: 'center',
    fontSize: 11,
    fontWeight: '700',
    color: '#9ca3af',
  },
  miniCalendarGrid: {
    marginTop: 10,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  miniCalendarCell: {
    width: '14.2857%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 9,
    borderRadius: 12,
    minHeight: 40,
  },
  miniCalendarCellMuted: {
    opacity: 0.38,
  },
  miniCalendarCellSelected: {
    backgroundColor: '#2563eb',
  },
  miniCalendarCellToday: {
    borderWidth: 1,
    borderColor: '#f59e0b',
  },
  miniCalendarCellText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#fff',
  },
  miniCalendarCellTextMuted: {
    color: '#9ca3af',
  },
  miniCalendarCellTextSelected: {
    color: '#fff',
  },
  miniCalendarDot: {
    marginTop: 4,
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: '#fbbf24',
  },
  miniCalendarDotRow: {
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  miniCalendarDotCustom: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: '#2563eb',
  },
  miniCalendarHint: {
    marginTop: 14,
    fontSize: 11,
    lineHeight: 16,
    color: '#9ca3af',
  },
  plannerShell: {
    marginTop: 14,
    borderRadius: 24,
    padding: 14,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ebe4d9',
  },
  plannerToolbar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
    marginBottom: 14,
    flexWrap: 'wrap',
  },
  plannerArrowRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  plannerArrowBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#f3f4f6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  plannerArrowText: {
    fontSize: 18,
    fontWeight: '800',
    color: '#111827',
  },
  plannerTodayBtn: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#f4efe7',
  },
  plannerTodayBtnText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#111827',
  },
  plannerViewSwitch: {
    flexDirection: 'row',
    gap: 8,
  },
  plannerViewBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#f9fafb',
  },
  plannerViewBtnActive: {
    backgroundColor: '#ef4444',
  },
  plannerViewBtnText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#6b7280',
    textTransform: 'capitalize',
  },
  plannerViewBtnTextActive: {
    color: '#fff',
  },
  weekHeaderRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  weekTimeHeader: {
    width: 62,
  },
  weekDayHeader: {
    width: 92,
    paddingVertical: 10,
    paddingHorizontal: 8,
    alignItems: 'center',
    borderLeftWidth: 1,
    borderLeftColor: '#f3f4f6',
  },
  weekDayHeaderActive: {
    backgroundColor: '#fff7ed',
  },
  weekDayName: {
    fontSize: 10,
    fontWeight: '700',
    color: '#9ca3af',
  },
  weekDayNameActive: {
    color: '#ef4444',
  },
  weekDayNumber: {
    marginTop: 4,
    fontSize: 18,
    fontWeight: '900',
    color: '#111827',
  },
  weekDayNumberActive: {
    color: '#ef4444',
  },
  weekGridRow: {
    flexDirection: 'row',
  },
  weekTimeCell: {
    width: 62,
    minHeight: 72,
    paddingTop: 10,
    paddingRight: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
    alignItems: 'flex-end',
  },
  weekTimeText: {
    fontSize: 10,
    color: '#9ca3af',
    fontWeight: '700',
  },
  weekGridCell: {
    width: 92,
    minHeight: 72,
    padding: 6,
    borderLeftWidth: 1,
    borderBottomWidth: 1,
    borderLeftColor: '#f3f4f6',
    borderBottomColor: '#f3f4f6',
    backgroundColor: '#fff',
  },
  weekGridCellSelected: {
    backgroundColor: '#fcfbf7',
  },
  weekGridCellToday: {
    backgroundColor: '#fff9f5',
  },
  weekEventCard: {
    borderLeftWidth: 3,
    borderRadius: 10,
    paddingVertical: 6,
    paddingHorizontal: 7,
    marginBottom: 4,
  },
  weekEventTime: {
    fontSize: 9,
    fontWeight: '800',
  },
  weekEventTitle: {
    marginTop: 3,
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '700',
    color: '#111827',
  },
  weekMoreText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#9ca3af',
  },
  agendaList: {
    gap: 10,
  },
  agendaCard: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'stretch',
    borderRadius: 16,
    padding: 12,
    backgroundColor: '#f9fafb',
    borderWidth: 1,
    borderColor: '#eef2f7',
  },
  agendaAccent: {
    width: 5,
    borderRadius: 999,
  },
  agendaTime: {
    fontSize: 11,
    fontWeight: '800',
    color: '#ef4444',
  },
  agendaTitle: {
    marginTop: 5,
    fontSize: 14,
    fontWeight: '800',
    color: '#111827',
  },
  agendaMeta: {
    marginTop: 4,
    fontSize: 12,
    color: '#6b7280',
  },

  taskComposerCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#e7e5e4',
    backgroundColor: '#fff',
    padding: 14,
  },
  taskTitleInput: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#fcfcfd',
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
  },
  taskModeRow: {
    marginTop: 12,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  taskModeChip: {
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#fff',
  },
  taskModeChipActive: {
    backgroundColor: '#111827',
    borderColor: '#111827',
  },
  taskModeChipText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#4b5563',
  },
  taskModeChipTextActive: {
    color: '#fff',
  },
  taskFieldsWrap: {
    marginTop: 14,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  taskFieldBlock: {
    minWidth: 104,
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
  },
  taskFieldLabel: {
    marginBottom: 6,
    fontSize: 11,
    fontWeight: '700',
    color: '#6b7280',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  taskFieldSelect: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#fcfcfd',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  taskFieldSelectValue: {
    fontSize: 14,
    fontWeight: '700',
    color: '#111827',
  },
  taskFieldSelectHint: {
    marginTop: 4,
    fontSize: 12,
    color: '#6b7280',
  },
  sheetOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(15, 23, 42, 0.28)',
  },
  sheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  sheetCard: {
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    backgroundColor: '#fffdf9',
    borderWidth: 1,
    borderColor: '#ebe4d9',
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 24,
    maxHeight: '90%',
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 86,
    height: 6,
    borderRadius: 999,
    backgroundColor: '#d6d3d1',
    marginBottom: 12,
  },
  sheetActionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  sheetActionSpacer: {
    minWidth: 78,
  },
  sheetActionRight: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
  },
  sheetGhostAction: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#e5ddd1',
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetGhostActionText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#111827',
  },
  sheetPrimaryAction: {
    borderRadius: 999,
    backgroundColor: '#111827',
    paddingHorizontal: 18,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetPrimaryActionText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#fff',
  },
  sheetTitle: {
    marginTop: 16,
    fontSize: 18,
    fontWeight: '900',
    color: '#111827',
  },
  sheetSubtitle: {
    marginTop: 6,
    fontSize: 13,
    color: '#6b7280',
  },
  sheetMiniCalendarWrap: {
    marginTop: 14,
  },
  sheetDetailPanel: {
    marginTop: 14,
    gap: 8,
  },
  sheetDetailNote: {
    marginTop: 4,
    fontSize: 12,
    lineHeight: 18,
    color: '#6b7280',
  },
  timeWheelRow: {
    marginTop: 14,
    flexDirection: 'row',
    gap: 10,
  },
  timeWheelGroup: {
    flex: 1,
  },
  timeWheelLabel: {
    marginBottom: 8,
    fontSize: 11,
    fontWeight: '700',
    color: '#6b7280',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    textAlign: 'center',
  },
  timeWheelColumn: {
    position: 'relative',
    height: TIME_WHEEL_ITEM_HEIGHT * (TIME_WHEEL_SIDE_ROWS * 2 + 1),
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#fff',
    overflow: 'hidden',
  },
  timeWheelGuideFrame: {
    position: 'absolute',
    left: 10,
    right: 10,
    top: TIME_WHEEL_ITEM_HEIGHT * TIME_WHEEL_SIDE_ROWS,
    height: TIME_WHEEL_ITEM_HEIGHT,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#d1d5db',
    zIndex: 2,
  },
  timeWheelItem: {
    height: TIME_WHEEL_ITEM_HEIGHT,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timeWheelItemText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#9ca3af',
  },
  timeWheelItemTextActive: {
    color: '#111827',
    fontWeight: '800',
  },
  monthYearSectionTitle: {
    marginTop: 16,
    marginBottom: 10,
    fontSize: 11,
    fontWeight: '700',
    color: '#6b7280',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  monthYearYearRow: {
    gap: 10,
    paddingRight: 8,
  },
  monthYearYearChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#fff',
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  monthYearYearChipActive: {
    borderColor: '#111827',
  },
  monthYearYearChipText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#6b7280',
  },
  monthYearYearChipTextActive: {
    color: '#111827',
  },
  monthYearGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  monthYearCell: {
    minWidth: '30%',
    flexGrow: 1,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#fff',
    paddingHorizontal: 12,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  monthYearCellActive: {
    borderColor: '#111827',
    backgroundColor: '#111827',
  },
  monthYearCellText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#6b7280',
  },
  monthYearCellTextActive: {
    color: '#fff',
  },
});

export default styles;
